// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/example/my-app-v2/ent/book"
	"github.com/example/my-app-v2/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[0].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = bookDescTitle.Validators[0].(func(string) error)
	// bookDescIsbn is the schema descriptor for isbn field.
	bookDescIsbn := bookFields[2].Descriptor()
	// book.IsbnValidator is a validator for the "isbn" field. It is called by the builders before save.
	book.IsbnValidator = bookDescIsbn.Validators[0].(func(string) error)
	// bookDescPrice is the schema descriptor for price field.
	bookDescPrice := bookFields[3].Descriptor()
	// book.DefaultPrice holds the default value on creation for the price field.
	book.DefaultPrice = bookDescPrice.Default.(float64)
}
